In [2]:
import pandas as pd

In [42]:
dementia = pd.read_excel("./Data/oasis_longitudinal.xlsx")
dementia

,Subject ID,MRI ID,Group,Visit,MR Delay,M/F,Hand,Age,EDUC,SES,MMSE,CDR,eTIV,nWBV,ASF
0,OAS2_0001,OAS2_0001_MR1,Nondemented,1,0,M,R,87,14,2.0,27.0,0.0,1986.550000,0.696106,0.883440
1,OAS2_0001,OAS2_0001_MR2,Nondemented,2,457,M,R,88,14,2.0,30.0,0.0,2004.479526,0.681062,0.875539
2,OAS2_0002,OAS2_0002_MR1,Demented,1,0,M,R,75,12,NaN,23.0,0.5,1678.290000,0.736336,1.045710
3,OAS2_0002,OAS2_0002_MR2,Demented,2,560,M,R,76,12,NaN,28.0,0.5,1737.620000,0.713402,1.010000
4,OAS2_0002,OAS2_0002_MR3,Demented,3,1895,M,R,80,12,NaN,22.0,0.5,1697.911134,0.701236,1.033623
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368,OAS2_0185,OAS2_0185_MR2,Demented,2,842,M,R,82,16,1.0,28.0,0.5,1692.880000,0.693926,1.036690
369,OAS2_0185,OAS2_0185_MR3,Demented,3,2297,M,R,86,16,1.0,26.0,0.5,1688.009649,0.675457,1.039686
370,OAS2_0186,OAS2_0186_MR1,Nondemented,1,0,F,R,61,13,2.0,30.0,0.0,1319.020000,0.801006,1.330540
371,OAS2_0186,OAS2_0186_MR2,Nondemented,2,763,F,R,63,13,2.0,30.0,0.0,1326.650000,0.795981,1.322890
372,OAS2_0186,OAS2_0186_MR3,Nondemented,3,1608,F,R,65,13,2.0,30.0,0.0,1332.944463,0.801248,1.316634

데이터 출처 : https://sites.wustl.edu/oasisbrains/home/oasis-2/             

### 데이터셋 설명       
60세 ~ 96세 사이의 150명의 피험자를 대상으로 한 데이터.
각 피험자(Subject ID)는 1년 이상의 간격을 두고 2회 이상 방문(MRI ID & Visit).                           
피험자는 모두 오른손잡이.           
피험자 72명은 연구기간 내내 비치매로 분류됨.            
64명은 최초 방문시 치매로 분류되어 이후 스캔에서도 치매로 분류됨.           
14명은 최초 방문시 비치매였으나 이후 치매로 분류됨.

In [49]:
72+64+14

150

컬럼 설명
- Subject ID
- MRI ID
- Group : Nondemented / Demented / Converted 
- Visit : 방문 횟수
- MR Delay 
- M/F : 성별
- Hand : 주요 사용 손
- Age : 나이
- EDUC : 교육 년수
- SES : Social Economic Status as assessed by the Hollingshead Index of Social Position and classified into categories from 1 (highest status) to 5 (lowest status) 사회 경제적 지위

- MMSE : Mini-Mental State Examination score (0 = worst ~ 30 = best)
    - 중증(9점 이하)                
    - 중등도(10~18점)               
    - 경도(19~23점)             
    - 24점(30점 만점) 이상의 점수는 정상적인 인지   
- CDR : Clinical Dementia Rating 
    - 0 = 정상
    - 0.5 = 매우 경도 치매
    - 1 = 경도 치매
    - 2 = 중증 치매
    - 3 = 심각한 치매
- eTIV : Estimated total intracranial volume, mm3 (추정된 총 두개 부피)
- nWBV : Normalized whole-brain volume, expressed as a percent of all voxels in the atlas-masked image that are labeled as gray or white matter by the automated tissue segmentation process
- ASF : Atlas scaling factor (unitless). Computed scaling factor that transforms native-space brain and skull to the atlas target (i.e., the determinant of the transform matrix)

In [74]:
dementia.head()

,Subject ID,MRI ID,Group,Visit,MR Delay,M/F,Hand,Age,EDUC,SES,MMSE,CDR,eTIV,nWBV,ASF
0,OAS2_0001,OAS2_0001_MR1,Nondemented,1,0,M,R,87,14,2.0,27.0,0.0,1986.550000,0.696106,0.883440
1,OAS2_0001,OAS2_0001_MR2,Nondemented,2,457,M,R,88,14,2.0,30.0,0.0,2004.479526,0.681062,0.875539
2,OAS2_0002,OAS2_0002_MR1,Demented,1,0,M,R,75,12,NaN,23.0,0.5,1678.290000,0.736336,1.045710
3,OAS2_0002,OAS2_0002_MR2,Demented,2,560,M,R,76,12,NaN,28.0,0.5,1737.620000,0.713402,1.010000
4,OAS2_0002,OAS2_0002_MR3,Demented,3,1895,M,R,80,12,NaN,22.0,0.5,1697.911134,0.701236,1.033623

In [ ]:
dementia.tail()

,Subject ID,MRI ID,Group,Visit,MR Delay,M/F,Hand,Age,EDUC,SES,MMSE,CDR,eTIV,nWBV,ASF
353,OAS2_0178,OAS2_0178_MR3,Nondemented,3,1447,F,R,93,14,2.0,30.0,0.0,1488.264336,0.735308,1.179226
354,OAS2_0179,OAS2_0179_MR1,Demented,1,0,M,R,79,20,1.0,26.0,0.5,1548.020000,0.710546,1.133710
355,OAS2_0179,OAS2_0179_MR2,Demented,2,652,M,R,81,20,1.0,26.0,0.5,1555.880000,0.690739,1.127980
356,OAS2_0181,OAS2_0181_MR1,Demented,1,0,F,R,74,12,NaN,26.0,0.5,1170.630000,0.732751,1.499190
357,OAS2_0181,OAS2_0181_MR2,Demented,2,539,F,R,75,12,NaN,NaN,1.0,1168.930000,0.741645,1.501370
358,OAS2_0181,OAS2_0181_MR3,Demented,3,1107,F,R,77,12,NaN,NaN,1.0,1158.567258,0.732767,1.514802
359,OAS2_0182,OAS2_0182_MR1,Demented,1,0,M,R,73,12,NaN,23.0,0.5,1661.270000,0.697563,1.056420
360,OAS2_0182,OAS2_0182_MR2,Demented,2,776,M,R,75,12,NaN,20.0,0.5,1653.728947,0.696097,1.061238
361,OAS2_0183,OAS2_0183_MR1,Nondemented,1,0,F,R,66,13,2.0,30.0,0.0,1495.240000,0.746302,1.173730
362,OAS2_0183,OAS2_0183_MR2,Nondemented,2,182,F,R,66,13,2.0,30.0,0.0,1506.120000,0.739969,1.165250
363,OAS2_0183,OAS2_0183_MR3,Nondemented,3,732,F,R,68,13,2.0,30.0,0.0,1505.930000,0.740058,1.165390
364,OAS2_0183,OAS2_0183_MR4,Nondemented,4,2107,F,R,72,13,2.0,30.0,0.0,1509.780019,0.723413,1.162421
365,OAS2_0184,OAS2_0184_MR1,Demented,1,0,F,R,72,16,3.0,24.0,0.5,1353.810000,0.733098,1.296340
366,OAS2_0184,OAS2_0184_MR2,Demented,2,553,F,R,73,16,3.0,21.0,1.0,1350.901987,0.707806,1.299132
367,OAS2_0185,OAS2_0185_MR1,Demented,1,0,M,R,80,16,1.0,28.0,0.5,1703.590000,0.710542,1.030180
368,OAS2_0185,OAS2_0185_MR2,Demented,2,842,M,R,82,16,1.0,28.0,0.5,1692.880000,0.693926,1.036690
369,OAS2_0185,OAS2_0185_MR3,Demented,3,2297,M,R,86,16,1.0,26.0,0.5,1688.009649,0.675457,1.039686
370,OAS2_0186,OAS2_0186_MR1,Nondemented,1,0,F,R,61,13,2.0,30.0,0.0,1319.020000,0.801006,1.330540
371,OAS2_0186,OAS2_0186_MR2,Nondemented,2,763,F,R,63,13,2.0,30.0,0.0,1326.650000,0.795981,1.322890
372,OAS2_0186,OAS2_0186_MR3,Nondemented,3,1608,F,R,65,13,2.0,30.0,0.0,1332.944463,0.801248,1.316634

In [ ]:
dementia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 373 entries, 0 to 372
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Subject ID  373 non-null    object
 1   MRI ID      373 non-null    object
 2   Group       373 non-null    object
 3   Visit       373 non-null    int64
 4   MR Delay    373 non-null    int64
 5   M/F         373 non-null    object
 6   Hand        373 non-null    object
 7   Age         373 non-null    int64
 8   EDUC        373 non-null    int64
 9   SES         354 non-null    float64
 10  MMSE        371 non-null    float64
 11  CDR         373 non-null    float64
 12  eTIV        373 non-null    float64
 13  nWBV        373 non-null    float64
 14  ASF         373 non-null    float64
dtypes: float64(6), int64(4), object(5)
memory usage: 43.8+ KB

In [75]:
dementia.isnull().sum()

Subject ID     0
MRI ID         0
Group          0
Visit          0
MR Delay       0
M/F            0
Hand           0
Age            0
EDUC           0
SES           19
MMSE           2
CDR            0
eTIV           0
nWBV           0
ASF            0
dtype: int64

#### 참여자 전체 수 & 진단 그룹별 수 확인

In [68]:
# 전체 참여자 수 확인
all = dementia['Subject ID'].nunique()
all

150

In [69]:
# 참여자 중 첫 방문시 치매 X → 추후 방문시 치매로 전환된 참여자 수 확인
converted = dementia[dementia['Group'] == 'Converted']['Subject ID'].nunique()
converted

14

In [70]:
# 연구 기간 내내 치매였던 참여자 수 확인
demented = dementia[dementia['Group'] == 'Demented']['Subject ID'].nunique()
demented

64

In [71]:
# 연구 기간 내내 정상이었던 참여자 수 확인
nondemented = dementia[dementia['Group'] == 'Nondemented']['Subject ID'].nunique()
nondemented

72

In [73]:
converted + demented + nondemented == all

True

In [80]:
dementia['Group'].value_counts()

Group
Nondemented    190
Demented       146
Converted       37
Name: count, dtype: int64

In [ ]:
# 변수간 상관관계